server:
    address: 127.0.0.1
    port: 8085
spring:
    datasource:
        data: classpath:data/categories.sql
        driver-class-name: org.h2.Driver
        name: library-db
        password: ''
        sql-script-encoding: UTF-8
        url: jdbc:h2:file:./src/main/resources/database/library-db
        username: sa
    h2:
        console:
            enabled: true
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
            ddl-auto: create-drop
        show-sql: true
    boot:
        admin:
            client:
                url: http://${server.address}:${server.port}